version: '3'
services:
  php:
    image: php:7.4-apache
    volumes:
      - ./php:/var/www/html
    ports:
      - '80:80'

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'

networks:
  default:
    external:
      name: my_network
